### ISSUE TITLE
Add notifications of new issues filed here

### ISSUE THREAD

**Issue by twm** [mrozekma/NoiseBot#34]
Obviously we all need up-to-the-minute updates on what's happening here.

**Comment by mrozekma** [comment]
Test comment

**Comment by mrozekma** [comment]
Test comment

**Comment by mrozekma** [comment]
Final test comment

**Comment by mrozekma** [comment]
Actual final test comment, probably. Maybe

**Comment by mrozekma** [comment]
Fixed in 408b6c1287b8cec61d988c6cdc9a24ed2ba0dbab
